### ISSUE TITLE
Error run cli-talk

### ISSUE THREAD

**Issue by webagroprom** [mrchainman/CLI-Talk#3]
**1. Downloads  beta on my server ( OS AlmaLinux)
2. Install pip3
3. pip3 install -r requirements.txt**

```
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1))

```

**run ./main.py**

```
Fetching your conversations ...
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    get_conversations()
  File "/root/CLI-Talk-1.0/bin/functions.py", line 46, in get_conversations
    m_conversations = (r_conversations.json())
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**How to fix a bug in beta ?**

**Comment by mrchainman** [comment]
Its been a while since I wrote this program, maybe there where api changes in the mean time, will look into it
